export type FootballGames = FootballGame[]

export interface FootballGame {
  _id: string
  HomeTeam: Team
  AwayTeam: Team
  Game?: Game
  Score: Score
  ScoringPlays: ScoringPlay[]
  AwayPassing: Passing[]
  AwayRushing: Rushing[]
  AwayReceiving: Receiving[]
  AwayKicking: Kicking[]
  AwayPunting: Punting[]
  AwayKickPuntReturns: KickPuntReturn[]
  AwayDefense: Defense[]
  HomePassing: Passing[]
  HomeRushing: Rushing[]
  HomeReceiving: Receiving[]
  HomeKicking: Kicking[]
  HomePunting: Punting[]
  HomeKickPuntReturns: KickPuntReturn[]
  HomeDefense: Defense[]
}

export interface StadiumDetails {
  StadiumID: number
  Name: string
  City: string
  State: string
  Country: string
  Capacity: number
  PlayingSurface: string
  GeoLat: string
  GeoLong: string
  Type: string
}

export interface Team {
  Key: string
  TeamID: number
  PlayerID: number
  City: string
  Name: string
  Conference: string
  Division: string
  FullName: string
  StadiumID: number
  ByeWeek: number
  AverageDraftPosition: string
  AverageDraftPositionPPR: string
  HeadCoach: string
  OffensiveCoordinator: string
  DefensiveCoordinator: string
  SpecialTeamsCoach: string
  OffensiveScheme: string
  DefensiveScheme: string
  UpcomingSalary: number
  UpcomingOpponent: string
  UpcomingOpponentRank: number
  UpcomingOpponentPositionRank: number
  UpcomingFanDuelSalary: any
  UpcomingDraftKingsSalary: number
  UpcomingYahooSalary: number
  PrimaryColor: string
  SecondaryColor: string
  TertiaryColor: string
  QuaternaryColor: any
  WikipediaLogoUrl: string
  WikipediaWordMarkUrl: string
  GlobalTeamID: number
  DraftKingsName: string
  DraftKingsPlayerID: number
  FanDuelName: string
  FanDuelPlayerID: number
  FantasyDraftName: string
  FantasyDraftPlayerID: number
  YahooName: string
  YahooPlayerID: number
  StadiumDetails: StadiumDetails
  AverageDraftPosition2QB: string
  AverageDraftPositionDynasty: string
}
export interface Game {
  GameKey: string
  Date: string
  SeasonType: number
  Season: number
  Week: number
  Stadium: string
  PlayingSurface: string
  Temperature: any
  Humidity: any
  WindSpeed: any
  AwayTeam: string
  HomeTeam: string
  AwayScore: number
  HomeScore: number
  TotalScore: number
  OverUnder: string
  PointSpread: string
  AwayScoreQuarter1: number
  AwayScoreQuarter2: number
  AwayScoreQuarter3: number
  AwayScoreQuarter4: number
  AwayScoreOvertime: number
  HomeScoreQuarter1: number
  HomeScoreQuarter2: number
  HomeScoreQuarter3: number
  HomeScoreQuarter4: number
  HomeScoreOvertime: number
  AwayTimeOfPossession: string
  HomeTimeOfPossession: string
  AwayFirstDowns: number
  HomeFirstDowns: number
  AwayFirstDownsByRushing: number
  HomeFirstDownsByRushing: number
  AwayFirstDownsByPassing: number
  HomeFirstDownsByPassing: number
  AwayFirstDownsByPenalty: number
  HomeFirstDownsByPenalty: number
  AwayOffensivePlays: number
  HomeOffensivePlays: number
  AwayOffensiveYards: number
  HomeOffensiveYards: number
  AwayOffensiveYardsPerPlay: string
  HomeOffensiveYardsPerPlay: string
  AwayTouchdowns: number
  HomeTouchdowns: number
  AwayRushingAttempts: number
  HomeRushingAttempts: number
  AwayRushingYards: number
  HomeRushingYards: number
  AwayRushingYardsPerAttempt: string
  HomeRushingYardsPerAttempt: string
  AwayRushingTouchdowns: number
  HomeRushingTouchdowns: number
  AwayPassingAttempts: number
  HomePassingAttempts: number
  AwayPassingCompletions: number
  HomePassingCompletions: number
  AwayPassingYards: number
  HomePassingYards: number
  AwayPassingTouchdowns: number
  HomePassingTouchdowns: number
  AwayPassingInterceptions: number
  HomePassingInterceptions: number
  AwayPassingYardsPerAttempt: string
  HomePassingYardsPerAttempt: string
  AwayPassingYardsPerCompletion: string
  HomePassingYardsPerCompletion: string
  AwayCompletionPercentage: string
  HomeCompletionPercentage: string
  AwayPasserRating: string
  HomePasserRating: string
  AwayThirdDownAttempts: number
  HomeThirdDownAttempts: number
  AwayThirdDownConversions: number
  HomeThirdDownConversions: number
  AwayThirdDownPercentage: string
  HomeThirdDownPercentage: string
  AwayFourthDownAttempts: number
  HomeFourthDownAttempts: number
  AwayFourthDownConversions: number
  HomeFourthDownConversions: number
  AwayFourthDownPercentage: string
  HomeFourthDownPercentage: string
  AwayRedZoneAttempts: number
  HomeRedZoneAttempts: number
  AwayRedZoneConversions: number
  HomeRedZoneConversions: number
  AwayGoalToGoAttempts: number
  HomeGoalToGoAttempts: number
  AwayGoalToGoConversions: number
  HomeGoalToGoConversions: number
  AwayReturnYards: number
  HomeReturnYards: number
  AwayPenalties: number
  HomePenalties: number
  AwayPenaltyYards: number
  HomePenaltyYards: number
  AwayFumbles: number
  HomeFumbles: number
  AwayFumblesLost: number
  HomeFumblesLost: number
  AwayTimesSacked: number
  HomeTimesSacked: number
  AwayTimesSackedYards: number
  HomeTimesSackedYards: number
  AwaySafeties: number
  HomeSafeties: number
  AwayPunts: number
  HomePunts: number
  AwayPuntYards: number
  HomePuntYards: number
  AwayPuntAverage: string
  HomePuntAverage: string
  AwayGiveaways: number
  HomeGiveaways: number
  AwayTakeaways: number
  HomeTakeaways: number
  AwayTurnoverDifferential: number
  HomeTurnoverDifferential: number
  AwayKickoffs: number
  HomeKickoffs: number
  AwayKickoffsInEndZone: number
  HomeKickoffsInEndZone: number
  AwayKickoffTouchbacks: number
  HomeKickoffTouchbacks: number
  AwayPuntsHadBlocked: number
  HomePuntsHadBlocked: number
  AwayPuntNetAverage: string
  HomePuntNetAverage: string
  AwayExtraPointKickingAttempts: number
  HomeExtraPointKickingAttempts: number
  AwayExtraPointKickingConversions: number
  HomeExtraPointKickingConversions: number
  AwayExtraPointsHadBlocked: number
  HomeExtraPointsHadBlocked: number
  AwayExtraPointPassingAttempts: number
  HomeExtraPointPassingAttempts: number
  AwayExtraPointPassingConversions: number
  HomeExtraPointPassingConversions: number
  AwayExtraPointRushingAttempts: number
  HomeExtraPointRushingAttempts: number
  AwayExtraPointRushingConversions: number
  HomeExtraPointRushingConversions: number
  AwayFieldGoalAttempts: number
  HomeFieldGoalAttempts: number
  AwayFieldGoalsMade: number
  HomeFieldGoalsMade: number
  AwayFieldGoalsHadBlocked: number
  HomeFieldGoalsHadBlocked: number
  AwayPuntReturns: number
  HomePuntReturns: number
  AwayPuntReturnYards: number
  HomePuntReturnYards: number
  AwayKickReturns: number
  HomeKickReturns: number
  AwayKickReturnYards: number
  HomeKickReturnYards: number
  AwayInterceptionReturns: number
  HomeInterceptionReturns: number
  AwayInterceptionReturnYards: number
  HomeInterceptionReturnYards: number
  AwaySoloTackles: number
  AwayAssistedTackles: number
  AwayQuarterbackHits: number
  AwayTacklesForLoss: number
  AwaySacks: number
  AwaySackYards: number
  AwayPassesDefended: number
  AwayFumblesForced: number
  AwayFumblesRecovered: number
  AwayFumbleReturnYards: number
  AwayFumbleReturnTouchdowns: number
  AwayInterceptionReturnTouchdowns: number
  AwayBlockedKicks: number
  AwayPuntReturnTouchdowns: number
  AwayPuntReturnLong: number
  AwayKickReturnTouchdowns: number
  AwayKickReturnLong: number
  AwayBlockedKickReturnYards: number
  AwayBlockedKickReturnTouchdowns: number
  AwayFieldGoalReturnYards: number
  AwayFieldGoalReturnTouchdowns: number
  AwayPuntNetYards: number
  HomeSoloTackles: number
  HomeAssistedTackles: number
  HomeQuarterbackHits: number
  HomeTacklesForLoss: number
  HomeSacks: number
  HomeSackYards: number
  HomePassesDefended: number
  HomeFumblesForced: number
  HomeFumblesRecovered: number
  HomeFumbleReturnYards: number
  HomeFumbleReturnTouchdowns: number
  HomeInterceptionReturnTouchdowns: number
  HomeBlockedKicks: number
  HomePuntReturnTouchdowns: number
  HomePuntReturnLong: number
  HomeKickReturnTouchdowns: number
  HomeKickReturnLong: number
  HomeBlockedKickReturnYards: number
  HomeBlockedKickReturnTouchdowns: number
  HomeFieldGoalReturnYards: number
  HomeFieldGoalReturnTouchdowns: number
  HomePuntNetYards: number
  IsGameOver: boolean
  GameID: number
  StadiumID: number
  AwayTwoPointConversionReturns: number
  HomeTwoPointConversionReturns: number
  ScoreID: number
  StadiumDetails: StadiumDetails
}

export interface Score {
  GameKey: string
  SeasonType: number
  Season: number
  Week: number
  Date: string
  AwayTeam: string
  HomeTeam: string
  AwayScore?: number
  HomeScore?: number
  Channel: string
  PointSpread: string
  OverUnder: string
  Quarter?: string
  TimeRemaining?: string
  Possession?: string
  Down?: number
  Distance: string
  YardLine?: number
  YardLineTerritory?: string
  RedZone?: string
  AwayScoreQuarter1?: number
  AwayScoreQuarter2?: number
  AwayScoreQuarter3?: number
  AwayScoreQuarter4?: number
  AwayScoreOvertime?: number
  HomeScoreQuarter1?: number
  HomeScoreQuarter2?: number
  HomeScoreQuarter3?: number
  HomeScoreQuarter4?: number
  HomeScoreOvertime?: number
  HasStarted: boolean
  IsInProgress: boolean
  IsOver: boolean
  Has1stQuarterStarted: boolean
  Has2ndQuarterStarted: boolean
  Has3rdQuarterStarted: boolean
  Has4thQuarterStarted: boolean
  IsOvertime: boolean
  DownAndDistance?: string
  QuarterDescription: string
  StadiumID: number
  LastUpdated: string
  GeoLat: any
  GeoLong: any
  ForecastTempLow: number
  ForecastTempHigh: number
  ForecastDescription: string
  ForecastWindChill: number
  ForecastWindSpeed: number
  AwayTeamMoneyLine: number
  HomeTeamMoneyLine: number
  Canceled: boolean
  Closed: boolean
  LastPlay: string
  Day: string
  DateTime: string
  AwayTeamID: number
  HomeTeamID: number
  GlobalGameID: number
  GlobalAwayTeamID: number
  GlobalHomeTeamID: number
  PointSpreadAwayTeamMoneyLine: number
  PointSpreadHomeTeamMoneyLine: number
  ScoreID: number
  StadiumDetails: StadiumDetails
  Status: string
  GameEndDateTime: any
  HomeRotationNumber: number
  AwayRotationNumber: number
  NeutralVenue: any
  RefereeID: number
  OverPayout: number
  UnderPayout: number
  HomeTimeouts?: number
  AwayTimeouts?: number
  DateTimeUTC: string
}

export interface ScoringPlay {
  GameKey: string
  SeasonType: number
  ScoringPlayID: number
  Season: number
  Week: number
  AwayTeam: string
  HomeTeam: string
  Date: string
  Sequence: number
  Team: string
  Quarter: string
  TimeRemaining: string
  PlayDescription: string
  AwayScore: number
  HomeScore: number
  ScoreID: number
}

export interface Passing {
  PlayerGameID: number
  PlayerID: number
  ShortName: string
  Name: string
  Team: string
  Number: number
  Position: string
  PositionCategory: string
  FantasyPosition: string
  FantasyPoints: string
  Updated: string
  PassingAttempts: number
  PassingCompletions: number
  PassingYards: number
  PassingTouchdowns: number
  PassingInterceptions: number
  PassingLong: number
  PassingSacks: number
  PassingSackYards: number
  PassingCompletionPercentage: string
  PassingYardsPerAttempt: string
  PassingYardsPerCompletion: string
  PassingRating: string
  TwoPointConversionPasses: number
  FumblesLost: number
}

export interface Rushing {
  PlayerGameID: number
  PlayerID: number
  ShortName: string
  Name: string
  Team: string
  Number: number
  Position: string
  PositionCategory: string
  FantasyPosition: string
  FantasyPoints: string
  Updated: string
  RushingAttempts: number
  RushingYards: number
  RushingTouchdowns: number
  RushingLong: number
  RushingYardsPerAttempt: number
  FumblesLost: number
  TwoPointConversionRuns: number
}

export interface Receiving {
  PlayerGameID: number
  PlayerID: number
  ShortName: string
  Name: string
  Team: string
  Number: number
  Position: string
  PositionCategory: string
  FantasyPosition: string
  FantasyPoints: string
  Updated: string
  Receptions: number
  ReceivingTargets: number
  ReceivingYards: number
  ReceivingTouchdowns: number
  ReceivingLong: number
  ReceivingYardsPerReception: string
  ReceivingYardsPerTarget: string
  ReceptionPercentage: string
  FumblesLost: number
  TwoPointConversionReceptions: number
}

export interface Kicking {
  PlayerGameID: number
  PlayerID: number
  ShortName: string
  Name: string
  Team: string
  Number: number
  Position: string
  PositionCategory: string
  FantasyPosition: string
  FantasyPoints: string
  Updated: string
  ExtraPointsMade: number
  ExtraPointsAttempted: number
  FieldGoalsMade: number
  FieldGoalsAttempted: number
  FieldGoalsLongestMade: number
  FieldGoalPercentage: string
  FieldGoalsMade0to19: number
  FieldGoalsMade20to29: number
  FieldGoalsMade30to39: number
  FieldGoalsMade40to49: number
  FieldGoalsMade50Plus: number
}

export interface Punting {
  PlayerGameID: number
  PlayerID: number
  ShortName: string
  Name: string
  Team: string
  Number: number
  Position: string
  PositionCategory: string
  FantasyPosition: string
  FantasyPoints: string
  Updated: string
  Punts: number
  PuntAverage: string
  PuntInside20: number
  PuntTouchbacks: number
  PuntYards: number
}

export interface KickPuntReturn {
  PlayerGameID: number
  PlayerID: number
  ShortName: string
  Name: string
  Team: string
  Number: number
  Position: string
  PositionCategory: string
  FantasyPosition: string
  FantasyPoints: string
  Updated: string
  KickReturns: number
  KickReturnYards: number
  KickReturnYardsPerAttempt: string
  KickReturnLong: number
  KickReturnTouchdowns: number
  PuntReturns: number
  PuntReturnYards: number
  PuntReturnYardsPerAttempt: string
  PuntReturnLong: number
  PuntReturnTouchdowns: number
  FumblesLost: number
}

export interface Defense {
  PlayerGameID: number
  PlayerID: number
  ShortName: string
  Name: string
  Team: string
  Number: number
  Position: string
  PositionCategory: string
  FantasyPosition: string
  FantasyPoints: string
  Updated: string
  Tackles: number
  SoloTackles: number
  AssistedTackles: number
  Sacks: string
  SackYards: number
  FumblesForced: number
  FumblesRecovered: number
  PassesDefended: number
  Interceptions: number
  InterceptionReturnYards: number
  InterceptionReturnTouchdowns: number
  TacklesForLoss: number
  QuarterbackHits: number
  FumbleReturnTouchdowns: number
  Safeties: number
}